select * from customer
limit 5;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender , sum(purchase_amount)
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id , purchase_amount
from customer
where purchase_amount >= (select avg(purchase_amount) from customer);

-- Q3. What are the top 5 products with the highest average review rating?

select item_purchased , round(avg(review_rating),2) as rating
from customer
group by item_purchased
order by rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type , avg(purchase_amount)
from customer
where shipping_type in ('Express' , 'Standard')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend 
-- and total revenue between subscribers and non-subscribers.

select subscription_status , 
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_amount,
round(sum(purchase_amount),2) as total_amount
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased , 
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*) , 2) 
as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal 
-- based on their total number of previous purchases, and show the count of each segment.

with cte as (SELECT customer_id,
       CASE 
           WHEN previous_purchases = 1 THEN 'New'
           WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customer)

select customer_segment , count(*) as "Number of Customer"
from cte 
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH purchase_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchased
    FROM customer
    GROUP BY category, item_purchased
),

cte as(select category ,item_purchased , total_purchased,
row_number() over(partition by category 
			order by total_purchased desc)
            as rn
from purchase_count  
)    

select category ,item_purchased , total_purchased
from cte
where rn <=3;  

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as total_customer
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?

select sum(purchase_amount) as total_spend,
age_group
from customer
group by age_group;